platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

install! 'cocoapods', :disable_input_output_paths => true

def download_spec! (options={})
  url = options[:url]
  FileUtils.mkdir_p './specs'
  Dir.chdir('./specs'){
    `curl -X GET '#{url}' -O -k -f -L`
  }
end

PLAYKIT_GIT='https://github.com/kaltura/playkit-ios.git'
PLAYKIT_BRANCH=ENV['PK_BRANCH'] || 'develop'

download_spec!(url: 'https://origins-mobile-products.s3.eu-west-1.amazonaws.com/hbs_onrewind_player/viacom18/1.0.45/onrewindshared.podspec')
download_spec!(url: 'https://origins-mobile-products.s3.eu-west-1.amazonaws.com/hbs_onrewind_player/viacom18/1.0.45/OnRewindSDK.podspec')

target 'OnRewindSample' do

  pod 'PlayKit', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH

  pod 'OnRewindSDK', :podspec => './specs/OnRewindSDK.podspec'
  pod 'onrewindshared', :podspec => './specs/onrewindshared.podspec'

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'PinLayout'

  pod 'Astrolabe'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
