platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

install! 'cocoapods', :disable_input_output_paths => true

target 'HBSSDKSample' do

  # sample
  pod 'RxSwift'
  pod 'RxCocoa'

  pod 'PinLayout'
  pod 'Astrolabe'

  pod 'Alidade'
  pod 'Alidade/Associatable'
  pod 'Alidade/Flowable'
  pod 'Alidade/FormatterPool'
  pod 'Alidade/UI'
  pod 'Alidade/String'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
